#!/bin/sh
#
# /etc/init.d/bulldog
#
# Author: Daniel Trugman <dtrugman@gmail.com>
#

### BEGIN INIT INFO
# Provides:          bulldog
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A powerful & portable generic watchdog application
# Description:       A powerful & portable generic watchdog application
#                    Allows monitoring of multiple applications simultaneously
### END INIT INFO

APP_NAME=bulldog
CONF_NAME=config.json
BIN_PATH=/usr/local/bin/${APP_NAME}
PID_PATH=/var/run/${APP_NAME}.pid

start() {
    sudo ${BIN_PATH}/${APP_NAME} service ${CONF_NAME} &> /dev/null &
}

stop() {
    # Args
    KILL_OPTIONS=${1}

    collect_status

    if [ "${PID_FROM_FILE}" != "" -a "${PID_FROM_FILE}" = "${PID_FROM_PS}" ]; then
        kill_by_pid "${KILL_OPTIONS}" ${PID_FROM_FILE}
    else
        kill_by_name "${KILL_OPTIONS}" ${APP_NAME}
    fi

    remove_pid_file
}

kill_by_pid() {
    # Args
    KILL_OPTIONS=${1}
    KILL_PID=${2}

    sudo kill ${KILL_OPTIONS} ${KILL_PID}
}

kill_by_name() {
    # Args
    KILL_OPTIONS=${1}
    KILL_NAME=${2}

    sudo killall ${KILL_OPTIONS} ${KILL_NAME}
}

remove_pid_file() {
    sudo rm -rf ${PID_PATH}
}

force_stop() {
    stop "-s 9"
}

restart() {
    stop
    start
}

force_reload() {
    force_stop
    start
}

collect_status() {
    PID_FROM_FILE=`cat ${PID_PATH} 2> /dev/null`
    PID_FROM_PS=`pgrep -f ${BIN_PATH}/${APP_NAME}`
}

status() {
    collect_status

    if [ "${PID_FROM_FILE}" = "" -a "${PID_FROM_FILE}" = "${PID_FROM_PS}" ]; then
        echo "${APP_NAME} not running"
    elif [ "${PID_FROM_FILE}" != "" -a "${PID_FROM_FILE}" = "${PID_FROM_PS}" ]; then
        echo "${APP_NAME} running @ ${PID_FROM_FILE}"
    else
        echo "${APP_NAME} in inconsistent state [${PID_FROM_FILE}|${PID_FROM_PS}]: please restart daemon"
    fi
}

case "$1" in
    start)
        start
        ;;
    
    stop)
        stop
        ;;

    restart)
        restart
        ;;
    
    force_reload)
        force_reload
        ;;

    status)
        status
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|force_reload|status}"
        ;;
esac